### ISSUE TITLE
hoek Vulnerability

### ISSUE THREAD

**Issue by upupming** [dominhhai/koa-log4js#13]
GitHub says "We found a potential security vulnerability in one of your dependencies."

![image](https://user-images.githubusercontent.com/24741764/44315376-1c13c300-a456-11e8-8b52-d9879e9fc211.png)

I found that the dependencies are so old, could you please update them?
```
$ npm ls hoek
hiters-server@1.0.0 E:\github\HITMers\server
`-- koa-log4@2.3.0
  `-- log4js@2.11.0
    `-- loggly@1.1.1
      `-- request@2.75.0
        `-- hawk@3.1.3
          +-- boom@2.10.1
          | `-- hoek@2.16.3
          +-- hoek@2.16.3
          `-- sntp@1.0.9
            `-- hoek@2.16.3
```

**Comment by dominhhai** [comment]
PR is welcome!

**Comment by diegocrzt** [comment]
I propose #14
