### ISSUE TITLE
Re: Versions

### ISSUE THREAD

**Issue by alt-jero** [dominhhai/koa-log4js#4]
Sorry to bother you again, but I have a suggestion which may solve the version issue:
If the 2.x branch is for Koa 2.x, would it make sense to add `"koa": "^2.0.0"` to the package.json dependencies? (And maybe even to the 1.x branch as `"koa": "^1.0.0"` for consistency?

**Comment by dominhhai** [comment]
v1: https://github.com/dominhhai/koa-log4js/blob/master/package.json#L3
v2: https://github.com/dominhhai/koa-log4js/blob/v2.x/package.json#L3

**Comment by alt-jero** [comment]
I mean:

```
"devDependencies": {
    "standard": "^6.0.8",
    "koa": "1.x.x"  //<<< Like that because if you then install it with koa 2.x it should complain, yes?
  }
```

**Comment by dominhhai** [comment]
Read [it](https://docs.npmjs.com/files/package.json), please.
