### ISSUE TITLE
update to  "log4js": "1.1.0" ？ 

### ISSUE THREAD

**Issue by jinwyp** [dominhhai/koa-log4js#7]
Hi：

now the dependency  log4js is 0.6 

Is there any plan to update to  "log4js" to  "1.1.0" ？  

When I use
```
log4js.configure(GConfig.log4jsConfig, { reloadSecs: 300 })
```

got warning :
WARN] log4js - Ignoring configuration reload parameter for "object" configuration.

**Comment by dominhhai** [comment]
@jinwyp PR is welcome!
